### ISSUE TITLE
Example App have Error 403

### ISSUE THREAD

**Issue by thequan1** [GoogleCloudPlatform/ios-docs-samples#11]
when i pressed the [Process Recorded Audio] button. I had Error 403
```
{
  "error": {
    "code": 403,
    "message": "Requests from this ios client application \u003cempty\u003e are blocked.",
    "status": "PERMISSION_DENIED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.Help",
        "links": [
          {
            "description": "Google developer console API key",
            "url": "https://console.developers.google.com/project/662893261214/apiui/credential"
          }
        ]
      }
    ]
  }
}
```

Then i found that populate the header with the bundle identitfier. It worked.
```
[request addValue:[[NSBundle mainBundle] bundleIdentifier] forHTTPHeaderField:@"X-Ios-Bundle-Identifier"];
```

**Comment by timburks** [comment]
@thequan1 Thanks for debugging and clarifying this. In my testing I didn't set the bundle identifier when I created the API key. I'll update the sample to send the bundle identifier in the header.
<img width="633" alt="screen shot 2016-08-04 at 10 09 34 am" src="https://cloud.githubusercontent.com/assets/405/17411182/0f8955a8-5a2c-11e6-925f-407b49b7769d.png">

**Comment by timburks** [comment]
The speech samples are updated in this commit: https://github.com/GoogleCloudPlatform/ios-docs-samples/commit/f30aa34521d8f0ec966e11434fd266e6f01ae218
