### ISSUE TITLE
Build failed: Library not found for -lBoringSSL-GRPC

### ISSUE THREAD

**Issue by W-quan** [GoogleCloudPlatform/ios-docs-samples#111]
### OS
ProductName:	Mac OS X
ProductVersion:	10.14.4
BuildVersion:	18E226
### POD
1.5.3
### Project
speech/Objective-C/Speech-gRPC-Streaming/Podfile
/Users/wzq/Workspace/iOS/Demo/ios-docs-samples/speech/Objective-C/Speech-gRPC-Streaming

---

**Comment by Yamashita-Torahito** [comment]
I am getting same issue,
@W-quan how did you solve this issue?
anyone solve this?

**Comment by idolize** [comment]
Same

**Comment by blueneel05** [comment]
anybody solved it ?? struggling with from last 3 days.

**Comment by santhoshvaddi** [comment]
@blueneel05  Couldn't able to reproduce the issue, Please go to your project folder where CLEANUP AND INSTALL-COCOAPODS are present.
Run command ./CLEANUP followed by ./INSTALL-COCOAPODS
This should resolve the import statement issues.

**Comment by blueneel05** [comment]
@santhoshvaddi thank you for the reply. Can you please guide me where do I find the "CLEANUP AND INSTALL-COCOAPODS" ?

**Comment by santhoshvaddi** [comment]
Please find them inside of your project folder (ios-docs-samples/speech/Objective-C/Speech-gRPC-Streaming)

From the terminal run the following commands `./CLEANUP` and `./INSTALL-COCOAPODS`

Attached screenshot for your reference. 

<img width="1911" alt="Screen Shot 2019-08-05 at 1 38 35 PM" src="https://user-images.githubusercontent.com/28930192/62493656-7d779380-b786-11e9-8dc8-a21f5303c972.png">
