### ISSUE TITLE
iOS 10 requires NSMicrophoneUsageDescription entry in the plist

### ISSUE THREAD

**Issue by mygzi** [GoogleCloudPlatform/ios-docs-samples#13]
FYI for those building for iOS 10 with Xcode 8: the previously-optional custom text for the microphone permission prompt is now mandatory, and the the demo speech app crashes without it when attempting to access the mic for the first time. 

Would be nice to include this property in a future commit, for now you can add an NSMicrophoneUsageDescription entry to the plist yourself.

**Comment by timburks** [comment]
@mygzi Thanks, I'll add that.

**Comment by timburks** [comment]
Done here: https://github.com/GoogleCloudPlatform/ios-docs-samples/commit/cdbe2d50c842e3b6f28cd2efb5f550d87398dc48
