### ISSUE TITLE
Session.pbobjc.h' file not found

### ISSUE THREAD

**Issue by matheussoliveira** [GoogleCloudPlatform/ios-docs-samples#142]
### OS
ProductName:	Mac OS X
ProductVersion:	10.15.4
BuildVersion:	19E266
### POD
1.8.4
### Project
dialogflow/stopwatch/Podfile
/Users/matheus/Desktop/ios-docs-samples/dialogflow/stopwatch

---

### Session.pbobjc.h' file not found | Feature

I'm trying to use the dialogflow and xcode can't import googleapis/Session.pbobjc and googleapis/Session.pbrbjc.h. Does anyone knows why?

**Comment by tansaku** [comment]
I have the same issue

**Comment by tansaku** [comment]
seems like #136 is describing the fix, but it's a bit unclear

**Comment by matheussoliveira** [comment]
Yeah, I given up on using it hahaha
Found out that was easier to integrate with python

**Comment by tansaku** [comment]
I seem to have gotten past this issue, by replacing with:

```
#import "google/cloud/dialogflow/v2beta1/Session.pbobjc.h"
#import "google/cloud/dialogflow/v2beta1/Session.pbrpc.h"
```

and going through all the pod files and replacing references to <googleapi/*> to "google/cloud/ etc", but that brings me up against a new error:

> Use of unresolved identifier 'MDCTextFieldColorThemer'

from 

```swift
    MDCTextFieldColorThemer.applySemanticColorScheme(colorScheme,
                                                     to: self.intentTextFieldController)
```

in `DialogflowViewController.swift`

**Comment by tansaku** [comment]
but I commented out that line, and the app actually built and loaded on my phone, with a new runtime error:

> Thread 1: Exception: "`[FIRApp configure];` (`FirebaseApp.configure()` in Swift) could not find a valid GoogleService-Info.plist in your project. Please download one from https://console.firebase.google.com/."

**Comment by tansaku** [comment]
fixed that by pulling in the plist file and now the thing builds and runs on my phone

![image](https://user-images.githubusercontent.com/30216/89696065-26168100-d90e-11ea-9150-163043d2aea7.png)

**Comment by tansaku** [comment]
but new error:

> Firebase registration token: <snip>
shouldWait: false, token: nil, error: NOT FOUND

fixed that by ensuring I had correct firebase project id, so passed that but app still stuck on the screen shown above ...

**Comment by alimsts** [comment]
@tansaku – Hi, can you please have a look at [this issue](https://github.com/GoogleCloudPlatform/ios-docs-samples/issues/147) I've reported on Google Speech API ? I appreciate your time and kind help. Thanks.
