### ISSUE TITLE
pod spec failure

### ISSUE THREAD

**Issue by air720boarder** [GoogleCloudPlatform/ios-docs-samples#2]
When trying to run 'pod install' while in the directory of the streaming example:

Fetching podspec for `googleapis` from `../../../googleapis`
[!] The `googleapis` pod failed to validate due to 3 errors:
    - ERROR | attributes: Missing required attribute `authors`.
    - ERROR | attributes: Missing required attribute `homepage`.
    - ERROR | attributes: Missing required attribute `source`.
    - ERROR | attributes: Missing required attribute `summary`.

This error is thrown.

**Comment by timburks** [comment]
We've seen that these additional attributes are required by the Cocoapods 1.0 beta. Our samples were tested with Cocoapods 0.39.0, and we'll be updating them to support Cocoapods 1.0 soon.

**Comment by timburks** [comment]
Please check after you've updated to include [this commit](https://github.com/GoogleCloudPlatform/ios-docs-samples/commit/3cd2a2fda435f72e1f6ff011a66314a1984f3da0).
