### ISSUE TITLE
How to convert AVAudioPCMBuffer into NSData ?

### ISSUE THREAD

**Issue by vikram-gupta** [GoogleCloudPlatform/ios-docs-samples#26]
Hi,

I want to tap into the AVAudioInputNode to capture the audio and perform speech recognition on it, so that other components of my application can still have access to audio stream.

However, AVAudioInputNode returns the data as AVAudioPCMBuffer but the speech recognition API expects NSData. How can I do the required conversion?

Thanks

**Comment by timburks** [comment]
Please check Apple documentation and forums for help for AVFoundation.
