### ISSUE TITLE
[Swift] Could not build modules during Archiving  and "Include of non-modular header inside framework module RxLibrary"

### ISSUE THREAD

**Issue by damienromito** [GoogleCloudPlatform/ios-docs-samples#30]
When I wanted to archive my app to build a Testflight app on itunes connect, I get several errors. Then I try with the demo project "Speech" and I get the same errors:

![screen shot 2016-12-15 at 16 28 41](https://cloud.githubusercontent.com/assets/603808/21238980/d7ab875c-c2e3-11e6-8477-79b577687bdf.png)

I found [this post](https://forums.developer.apple.com/thread/23554) on the first issue, but I couldn't manage.

**Comment by damienromito** [comment]
I managed to archive the app just by commenting the line.This create a warning but the voice detection works well.

![screen shot 2016-12-16 at 14 10 24](https://cloud.githubusercontent.com/assets/603808/21271370/8b13ba0c-c399-11e6-8098-e2f294c23a1d.png)

**Comment by tsuyoshiishikawa** [comment]
I resolved!

**Comment by damienromito** [comment]
How?

**Comment by tsuyoshiishikawa** [comment]
I only commented out.
![2017-05-23 21 28 20](https://cloud.githubusercontent.com/assets/902572/26354303/fc9c7858-3ffe-11e7-999f-e265da2d1807.png)

**Comment by damienromito** [comment]
Yes, this manipulation is now in the BUILDFIXES file ;)

https://github.com/GoogleCloudPlatform/ios-docs-samples/blob/master/speech/Swift/Speech-gRPC-Streaming/BUILDFIXES

**Comment by AppHero2** [comment]
Firebase Firestore could not build modules while archiving app

**Comment by jacobo360** [comment]
Will this be fixed in any upcoming updates soon? Every time I install a new dependency I need to go back and comment this line before archiving.

**Comment by ramsalazar** [comment]
@jacobo360 As of now this issue has been fixed already on the 1.13.0 version release on gRPC. I just did it on my project and update the pod file to grab the updated version because the previous version I had is 1.12.0

**Comment by jacobo360** [comment]
Brilliant. Thanks!

**Comment by raghaaavvvv** [comment]
I figured out the problem, all of the deployment targets need to be the same. That is, in the project file, the target, and the pods project as well.
