### ISSUE TITLE
swift examples dont compile due to error with boringSSL pod

### ISSUE THREAD

**Issue by Daij-Djan** [GoogleCloudPlatform/ios-docs-samples#39]
hi,
the swift example doesnt compile due to error with boringSSL pod

./Pods/BoringSSL/include/openssl/module.modulemap:1:20: Redefinition of module 'openssl'

the installation:
```
Installing !ProtoCompiler (3.0.2)
Installing !ProtoCompiler-gRPCPlugin (1.0.2)
Installing BoringSSL (7.0)
Installing Protobuf (3.2.0)
Installing gRPC (1.0.2)
Installing gRPC-Core (1.0.2)
Installing gRPC-ProtoRPC (1.0.2)
Installing gRPC-RxLibrary (1.0.2)
Installing googleapis (0.0.1)
Generating Pods project
```

**Comment by Daij-Djan** [comment]
applies to Speech-gRPC-Streaming sample as well as the stickynotes demo

**Comment by kirualex** [comment]
In Xcode 8.3 framework declarations need to have the same filename as Framework. BoringSSL pod only names it modulemap.modulemap.

So solution is to change
`Pods/BoringSSL/include/openssl/module.modulemap`
to
`Pods/Target Support Files/BoringSSL/BoringSSL.modulemap.`

**Comment by Daij-Djan** [comment]
thanks!

**Comment by derpoliuk** [comment]
This did work for me without changing `module.modulemap`: https://github.com/GoogleCloudPlatform/ios-docs-samples/issues/4#issuecomment-244462318

**Comment by jianming** [comment]
kirualex, can you explain more about the solution? I saw the Pods/Target Support Files/BoringSSL/BoringSSL.modulemap is auto generated.
