### ISSUE TITLE
Archive swift ios project with speech lib take errors

### ISSUE THREAD

**Issue by phhuan** [GoogleCloudPlatform/ios-docs-samples#47]
I integrated speech api to my swift ios project with build and run demo on device successfully. But when i make archive to prepare to submit app, it takes 4 errors as following:
1. Could not build module 'RxLibrary'. 
#import <RxLibrary/GRXWriter.h>
2. Could not build module 'GRPCClient'.
#import <GRPCClient/GRPCCall.h>
3. Could not build module 'ProtoRPC'.
#import <ProtoRPC/ProtoService.h>

Could anyone please help me to fix thems?
thanks,

**Comment by wenxin3262** [comment]
Manually fix everything states in there: https://github.com/GoogleCloudPlatform/ios-docs-samples/blob/master/speech/Swift/Speech-gRPC-Streaming/BUILDFIXES

Also, comment out line in `gRPC-umbrella.h`
```
//#import "internal_testing/GRPCCall+InternalTests.h"
```

**Comment by ajayghodadra** [comment]
Did anyone fix this?

**Comment by phhuan** [comment]
Thank wenxin3262, i fixed it.

**Comment by ajayghodadra** [comment]
@phhuan Could you please tell me the fix?

**Comment by phhuan** [comment]
@ajayghodadra Please follow this BuildFixes: https://github.com/GoogleCloudPlatform/ios-docs-samples/blob/master/speech/Swift/Speech-gRPC-Streaming/BUILDFIXES
Try to comments and replace all of import lines in BuildFixes. I miss one line and take this error.

**Comment by ajayghodadra** [comment]
@phhuan I am following exactly the same build fixes and I can successfully run the project. This error comes up when I try to archive and make an ipa. Could you tell me which line did you miss? and Can you make an archive and can create an ipa with that?

**Comment by phhuan** [comment]
@ajayghodadra i have the same problem with you before. Only error in archive process. I fixed it.
 Be sure you do first step of BUILDFIXES.

1) comment out this line:

#import "transformations/GRXMappingWriter.h"

from gRPC-RxLibrary-umbrella.h. You'll see it when
you build and get an error saying "include of non-modular
header inside framework module."

You should comment it like this:
//#import "transformations/GRXMappingWriter.h"

**Comment by Satchitananda** [comment]
Still not fixed?
