### ISSUE TITLE
Issue with protoc version

### ISSUE THREAD

**Issue by kanjiroushi** [GoogleCloudPlatform/ios-docs-samples#5]
When I follow the readme and compiule the streaming version of the speech recognition demo, I get an error in the CloudSpeech.pbobjc.h 

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30000
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

When I check the command line protoc --version, I get
libprotoc 3.0.0

Thus I don't understand the error and don't know how to fix it.

Am I the only one to experience this?

**Comment by hadfield** [comment]
we have the same issue.

**Comment by martinc** [comment]
Same here.

**Comment by dkobylarz** [comment]
same here. anyone?

**Comment by timburks** [comment]
Sorry about the trouble. I've been able to build with a previously-installed protoc and after freshly reinstalling. When I run the "RUNME" script in a fresh clone, I see the following:

===
$ sh RUNME
Install Cocoapod dependencies
Analyzing dependencies
Fetching podspec for 'googleapis' from '../../../googleapis'
Downloading dependencies
Installing BoringSSL (2.0)
Installing Protobuf (3.0.0-beta-2)
Installing gRPC (0.12.0)
Installing googleapis (0.0.1)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `Speech.xcworkspace` for this project from now on.
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 4 total pods installed.
Open the project workspace in Xcode
Now press the run button!`

===

Also,

protoc --version returns "libprotoc 3.0.0" and pod --version returns "1.0.0".

and when I search for "#define GOOGLE_PROTOBUF_OBJC_GEN_VERSION", I find it in GPBBootstrap.h with value 30000.

My test systems are running Xcode 7.2 and 7.3.

I'll continue investigating -- but if you're having problems and seeing versions that differ from any of these, that would be great to know.

**Comment by kanjiroushi** [comment]
Still get the issue with a clean clone.
On the console, the protoc version returns libprotoc 3.0.0 and pod version is 1.0.0

Indeed when I search for #define GOOGLE_PROTOBUF_OBJC_GEN_VERSION  I get 30001 in the GPBBootstrap.h file

**Comment by kanjiroushi** [comment]
On the RUNME script I get 
Installing Protobuf (3.0.0-beta-3)
that differs from you

**Comment by timburks** [comment]
I've pushed the googleapis.podspec change that kanjiroushi mentioned above. 

3.0.0-beta-3 requires changes to protoc that aren't in the official release yet, so the podspec will need updating again when protoc is updated.

**Comment by hadfield** [comment]
i'm now able to get it working in the simulator after using "pod" to revert to an older version of protoc.

**Comment by gankit** [comment]
I resolved this issue after installing protoc with instructions from here: https://github.com/grpc/grpc/tree/master/src/objective-c#cocoapods

**Comment by timburks** [comment]
The podspecs in the samples now download and use a precompiled protoc that matches the Protobuf library.

**Comment by adarshroy** [comment]
googleapis.podspec file has following content: 

```
Pod::Spec.new do |s|
  s.name     = 'googleapis'
  s.version  = '0.0.1'
  s.license  = 'Apache 2.0'
  s.authors  = { 'Google Inc.' => 'timburks@google.com'}
  s.homepage = 'http://github.com/GoogleCloudPlatform/ios-docs-samples'
  s.source   = { :git => 'https://github.com/GoogleCloudPlatform/ios-docs-samples.git',
                 :tag => '0.0.1' }
  s.summary  = 'Service definitions for Google Cloud Platform APIs'	  

  s.ios.deployment_target = '7.1'
  s.osx.deployment_target = '10.9'

 # Run protoc with the Objective-C and gRPC plugins to generate protocol messages and gRPC clients.
  s.dependency "!ProtoCompiler-gRPCPlugin", "~> 1.0.0-pre1.1"

  # Pods directory corresponding to this app's Podfile, relative to the location of this podspec.
  pods_root = 'Pods'

  # Path where Cocoapods downloads protoc and the gRPC plugin.
  protoc_dir = "#{pods_root}/!ProtoCompiler"
  protoc = "#{protoc_dir}/protoc"
  plugin = "#{pods_root}/!ProtoCompiler-gRPCPlugin/grpc_objective_c_plugin"

  # Run protoc with the Objective-C and gRPC plugins to generate protocol messages and gRPC clients.
  # You can run this command manually if you later change your protos and need to regenerate.  
  s.prepare_command = <<-CMD
    #{protoc} \
        --objc_opt=named_framework_to_proto_path_mappings_path=./protomap \
        --plugin=protoc-gen-grpc=#{plugin} \
        --objc_out=. \
        --grpc_out=. \
        -I . \
        -I #{protoc_dir} \
        google/*/*.proto google/*/*/*/*.proto
  CMD

  # The --objc_out plugin generates a pair of .pbobjc.h/.pbobjc.m files for each .proto file.
  s.subspec "Messages" do |ms|
    ms.source_files = "google/**/*.pbobjc.{h,m}"
    ms.header_mappings_dir = "."
    ms.requires_arc = false
    ms.dependency "Protobuf"
  end

  # The --objcgrpc_out plugin generates a pair of .pbrpc.h/.pbrpc.m files for each .proto file with
  # a service defined.
  s.subspec "Services" do |ss|
    ss.source_files = "google/**/*.pbrpc.{h,m}"
    ss.header_mappings_dir = "."
    ss.requires_arc = true
    ss.dependency "gRPC-ProtoRPC"
    ss.dependency "#{s.name}/Messages"
  end
  
  s.pod_target_xcconfig = {
    'GCC_PREPROCESSOR_DEFINITIONS' => '$(inherited) GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS=1',
	  'USER_HEADER_SEARCH_PATHS' => '$SRCROOT/..'
  }
  
end
```

I am getting the error in terminal (for my iOS project): 
Error installing googleapis  -> googleapis (0.0.1)
