### ISSUE TITLE
Error when regenerating .proto file

### ISSUE THREAD

**Issue by alhennessey92** [GoogleCloudPlatform/ios-docs-samples#54]
Please execute this shell command then replace it with your console output.

### ProductName:	Mac OS X
ProductVersion:	10.12.5
BuildVersion:	16F73
pod --version 1.2.1
git ls-tree --full-name --name-only HEAD Podfile
/Users/Me/Desktop/ios_apps/Main/Epic/protos
---

### Problem | Feature

I am trying to manually regenerate my protos files but i get the error

> -bash: !ProtoCompiler/protoc: event not found

The command i am running is 

`../Pods/!ProtoCompiler/protoc —plugin=protoc-gen-grpc=../Pods/!ProtoCompiler-gRPCPlugin/grpc_objective_c_plugin —objc_out=. —grpc_out=. -I . -I ../Pods/!ProtoCompiler *.proto`

Thanks for the help

**Comment by yoitsro** [comment]
You need to escape the `!` marks. 

So you need to use this command:

`../Pods/\!ProtoCompiler/protoc —plugin=protoc-gen-grpc=../Pods/\!ProtoCompiler-gRPCPlugin/grpc_objective_c_plugin —objc_out=. —grpc_out=. -I . -I ../Pods/!ProtoCompiler *.proto`

**Comment by yoitsro** [comment]
The command I ended up using was this:

```
../Pods/\!ProtoCompiler/protoc \
  --plugin=protoc-gen-grpc=../Pods/\!ProtoCompiler-gRPCPlugin/grpc_objective_c_plugin \
  --objc_out=. \
  --grpc_out=. \
  -I . \
  -I ../Pods/\!ProtoCompiler \
  *.proto
```

**Comment by timburks** [comment]
This appears to be resolved in the comments.
