### ISSUE TITLE
protobuf directory missing

### ISSUE THREAD

**Issue by martinc** [GoogleCloudPlatform/ios-docs-samples#6]
On build, I'm getting a file not found error for google/protobuf/Descriptor.pbobjc.h

Within the file google/api/Annotations.pbobjc.m

The whole protobuf folder seems to be missing from the google directory.

**Comment by tboyce12** [comment]
Hi @martinc ,

I have the same issue. Did you find a solution?

Thanks,
Tom

**Comment by martinc** [comment]
@tboyce12 I think I found a fix for this specific issue, but had lots of other issues and have put this on the back burner. Need to revisit it and try again. The fix may of had to do with changing the required pod version of Protobuf.
