### ISSUE TITLE
Got error when running SETUP for stickynotesapi's Go

### ISSUE THREAD

**Issue by edopelawi** [GoogleCloudPlatform/ios-docs-samples#62]
### OS
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G29
### POD
1.1.1
### Project
[Redacted]/ios-docs-samples/solutions/stickynoteapi/gRPC/Go/go

---

### Problem

Hey everyone,

I tried to run the sample to get a better grasp for gRPC, but the SETUP script fails. I got this error when running the `go get server` command:

```
# golang.org/x/net/http2
go/src/golang.org/x/net/http2/transport.go:227: req.Cancel undefined (type *http.Request has no field or method Cancel)
go/src/golang.org/x/net/http2/transport.go:231: req.Cancel undefined (type *http.Request has no field or method Cancel)
go/src/golang.org/x/net/http2/transport.go:902: req.Cancel undefined (type *http.Request has no field or method Cancel)
```

There are other errors after this step, but I think it's somewhat related. I have zero experience in Golang, apologies if I'm pretty clueless on this.

Any help would be appreciated!

Stay awesome,

**Comment by edopelawi** [comment]
Anyone?

**Comment by timburks** [comment]
Hi, I'm unable to reproduce this using this Go version: 
```
$ go version
go version go1.9.2 darwin/amd64
```

**Comment by timburks** [comment]
Please use the latest version of Go and reopen if this is still a problem.
