### ISSUE TITLE
Control may reach end of non-void function

### ISSUE THREAD

**Issue by arm0nic** [GoogleCloudPlatform/ios-docs-samples#63]
Please execute this shell command then replace it with your console output.

```
### OS
ProductName:	Mac OS X
ProductVersion:	10.13.1
BuildVersion:	17B48

### POD
1.3.1

### Xcode
9.1
Swift 4
```

---

### Problem

During the last weeks I had to implement Google Cloud Speech in a test application.  I am really happy about the result especially the detection rate is quite impressive. However the process of implementing it in my Xcode 9 project was quite a struggle. I experienced several issues which I could solve due to others who kindly shared their workaround (e.g. redefinition of openssl module #45) but the one that gave me lots of headaches I had to fix myself:

**Error:** `Control may reach end of non-void function`

Xcode did not tell me details about where I needed to start looking but after hours of googling and trial and error I found what had caused the compiler to stop the building process:

`#define GPR_FORBID_UNREACHABLE_CODE 1` 

in 

`Pods > gRPC-Core > Interface > port_platform.h`

on **line 243**.

**Solution:**

Commenting the line solved the problem for me. I don't know if that's a proper workaround but so far everything works fine for me. 

Hope I could save you some headaches ;)

**Comment by suindong** [comment]
![Uploading return_type.png…]()
You can change the "Mismatched Return Type" from "Yes(treat as error)" to "YES" in target gRPC-Core, it will solve the problem.

**Comment by timburks** [comment]
Thanks for raising this! I've reproduced the problem and found that updating the gRPC version in [this commit](https://github.com/GoogleCloudPlatform/ios-docs-samples/commit/61cdfca34e174b356f8693647d81f02ba6fdb620) fixed it.

**Comment by grehce** [comment]
A similar issue is surfacing for channel_init.c

"Control may reach end of non-void function"

I am uncertain as to how to resolve.

https://www.dropbox.com/s/hocpky9zeyj7ybt/Screenshot%202018-08-24%2000.01.42.png?dl=0

**Comment by grehce** [comment]
Must re-run pod update in order for gRPC files to propagate with new files.

https://github.com/GoogleCloudPlatform/ios-docs-samples/issues/91
