### ISSUE TITLE
grpc streaming error in sample app

### ISSUE THREAD

**Issue by hadfield** [GoogleCloudPlatform/ios-docs-samples#7]
the ios streaming sample app now returns this error after about a second of audio processing:
{
    error {
      code: 10
      message: "Audio data is being streamed too fast. Please stream audio data approximately at real time."
    }
}

**Comment by hadfield** [comment]
this was also reported here: https://groups.google.com/forum/#!topic/cloud-speech-discuss/vY_akkl1dAA

**Comment by timburks** [comment]
Marc, thank you. I've filed a bug report with the speech API team on this.

**Comment by hadfield** [comment]
thanks!

**Comment by timburks** [comment]
Marc, what device are you using to test this? I'm unable to reproduce the problem with an iPhone 6s Plus.

**Comment by hadfield** [comment]
this is in xcode, emulating iphone 6s.  also, many others have reported the problem in the forum.

**Comment by timburks** [comment]
Thanks, I see it now in the simulator. The error is inconsistent but frequent. I seem to get better results when I set the sample rate to 8kHz. Currently that requires changes in two places...
AudioController.m:
    sampleRate = 16000;
and SpeechRecognitionService.m:
    initialRecognizeRequest.sampleRate = 16000;
The Speech API team is investigating this now.

**Comment by hadfield** [comment]
changing the sample rate to alternate values has no effect on my end.
also, errors occur nearly always and immediately.

**Comment by timburks** [comment]
We're still investigating this, but I seem to get better results when I reduce the size of audio chunks that we send to the service. If you could try this, you'd find the related code in ViewController.m:

  if ([self.audioData length] > 16384) {

If you replace 16384 with 0, audio chunks will be sent as soon as they are received from the audio unit, and at least in my tests, recognition runs without errors.

**Comment by hadfield** [comment]
so far that works locally within xcode for me simulating iphone 6s.

**Comment by emiled** [comment]
I'm experiencing the same issue, and have had some results when altering the sample rate, and the audioData length variable. 

However the results have been inconsistent and i'm currently still experiencing the error.

**Comment by timburks** [comment]
We believe this has been fixed.

**Comment by korovkin** [comment]
i am experiencing the same issue

**Comment by korovkin** [comment]
we are streaming AMR data at 8Khz, our buffer size is about 256 bytes per write request. 

please help debug.
