### ISSUE TITLE
Refresh grpc streaming google speech api classes

### ISSUE THREAD

**Issue by dkobylarz** [GoogleCloudPlatform/ios-docs-samples#8]
Hi,
is it possible to regenerate grpc streaming google speech api classes with new fields like InitialRecognizeRequest#speech_context ?

**Comment by timburks** [comment]
We've updated the cloud_speech.proto to v1beta1, which includes the speech_context field in the RecognitionConfig message. A corresponding "speechContext" field is the generated code for the RecognitionConfig class. Hopefully the generated headers contain enough information to be useful to you. If not, please follow up with any other questions.
