### ISSUE TITLE
'google/cloud/speech/v1/CloudSpeech.pbobjc.h' file not found

### ISSUE THREAD

**Issue by grehce** [GoogleCloudPlatform/ios-docs-samples#89]
Workspace upon build compile is unable to locate CloudSpeech.pbobjc.h; however, I do see it in the folder view finder per screenshot below:
https://www.dropbox.com/s/33pu11vcpckwi6v/Screenshot%202018-08-13%2012.26.03.png?dl=0

Not sure how to properly locate the file. I've tried removing the file location reference and dropping the file directly into the reference and still get the above error.

```
### OS
Graces-MBP:Speech-gRPC-Streaming grehce$ sw_vers 
ProductName:	         Mac OS X
ProductVersion:	10.13.4
BuildVersion:	        17E199

### POD
Graces-MBP:           Speech-gRPC-Streaming grehce$ pod --version

echo "### Project"
git ls-tree --full-name --name-only HEAD Podfile
pwd
echo ''
1.5.3

### Project
Graces-MBP:Speech-gRPC-Streaming grehce$ git ls-tree --full-name --name-only HEAD Podfile
speech/Swift/Speech-gRPC-Streaming/Podfile
Graces-MBP:Speech-gRPC-Streaming grehce$ pwd
/Users/grehce/Dropbox/grace/Kintsugi/Xcode Testing/ios-docs-samples/speech/Swift/Speech-gRPC-Streaming

---

### Problem: Unable to locate CloudSpeech.pbobjc.h file | Speech

**Comment by grehce** [comment]
Per @morganchen12, I was able to locate and add the path to the Header Search Path but am still getting the same compiler error: Annotations.pbobj.h file not found."

Please advise.
https://www.dropbox.com/s/gxbsc9qreiua8fl/Screenshot%202018-08-20%2018.45.30.png?dl=0

**Comment by grehce** [comment]
https://stackoverflow.com/questions/51957256/google-speech-to-text-ios-app-example-could-not-build-module-googleapis

**Comment by morganchen12** [comment]
@grehce can you share your project in its current state?

**Comment by grehce** [comment]
@morganchen12 sure, here is my forked copy: https://github.com/grehce/ios-docs-samples

**Comment by morganchen12** [comment]
Looks like you were just missing a few instructions in the README.

Running the `INSTALL_COCOAPODS` script in the same directory as the xcodeproj will correctly fix up the headers for you.

**Comment by grehce** [comment]
I definitely have the cocoapods or I wouldn't have been able to open the workspace file.

https://www.dropbox.com/s/s8gna8zs49bcd0h/Screenshot%202018-08-23%2013.51.38.png?dl=0

**Comment by grehce** [comment]
Ah, I had run this but didn't notice that it was incomplete, "The file /Users/grehce/Speech.xcworkspace does not exist," I only saw the last row, "[Process completed]":
https://www.dropbox.com/s/hc4qifzfkoq7mvl/Screenshot%202018-08-23%2014.49.26.png?dl=0

I have the .exe file in the same folder as the Speech.xcworkspace file. Should it be placed somewhere else to execute successfully?

**Comment by grehce** [comment]
@morganchen12 I've attempted to integrate googleapis Speech into my own project and am getting the following errors:
`Could not build Objective-C module 'googleapis'`
`'google/cloud/speech/v1/CloudSpeech.pbobjc.h' file not found`

I've shared the private repo with you.

**Comment by LogiLeap** [comment]
Hi @grehce Akahs here,
This guide help us for fixing that issue **[BUILDFIXES](https://github.com/GoogleCloudPlatform/ios-docs-samples/blob/master/speech/Swift/Speech-gRPC-Streaming/BUILDFIXES)**

Get that from here **[Source](https://github.com/GoogleCloudPlatform/ios-docs-samples/issues/20#issuecomment-245635971)**

**Comment by grehce** [comment]
@LogiLeap Thanks Akash, per screenshot, I've tried running BUILDFIXES on my app dir and believe the folder hierarchy is affecting the script's ability to locate the files to update. I've re-ordered my xcode project to the same folder hierarchy and the script is still unable to replace the naming references. I've also manually updated the file with a replace all and this seems to create more build errors.

**Comment by grehce** [comment]
More googleapi issues:

https://www.dropbox.com/s/qnpnbo4qxl7bwfi/Screenshot%202018-08-26%2001.00.00.png?dl=0

Here are the specific errors when I attempt to Archive in preparation for TestFlight:


Lexical or Preprocessor Issue:
1 Include of non-modular header inside framework module 'RxLibrary': '/Users/grehce/Library/Developer/Xcode/DerivedData/Speech-envuamxvrexdawfyhixbmgnxgzvn/Build/Intermediates.noindex/ArchiveIntermediates/Speech/BuildProductsPath/Release-iphoneos/gRPC-RxLibrary/RxLibrary.framework/Headers/transformations/GRXMappingWriter.h'

Parse Issue:
2 #import <RxLibrary/GRXWriter.h> Could not build module 'RxLibrary'
3 #import <GRPCClient/GRPCCall.h> Could not build module 'GRPCClient'
4 #import <ProtoRPC/ProtoService.h> Could not build module 'ProtoRPC'

**Comment by morganchen12** [comment]
@grehce sorry for the delay, I'm taking a look at the project now. It seems to be referencing files outside the repository scope.

I'll open a new issue on the repo you shared.

**Comment by grehce** [comment]
Thanks @morganchen12! I was able to work with @logileap in rebuilding the pod with the operation and speech header changes. It was a bit of a mess but the latest build from my private repo that you’re shared on should build and was able to archive to push to TestFlight this morning for initial beta feedback.

**Comment by LogiLeap** [comment]
Hi @peterpaohuang please take a look on my [comment ](https://github.com/GoogleCloudPlatform/ios-docs-samples/issues/89#issuecomment-415937340) it will help you to fix that issue.

**Comment by arthursalgado** [comment]
Semantic Error..

Class 'Speech' defined without specifying a base class
Speech' cannot use 'super' because it is a root class
....


ARC Semantic Issue..

No known class method for selector 'alloc'
No visible @interface for 'Speech' declares the selector 'RPCToMethod:requestsWriter:responseClass:responsesWriteable:'

Anyone else ?? Thanks.

**Comment by arthursalgado** [comment]
@LogiLeap  any update ? Thanks.
