### ISSUE TITLE
GRPCProtoCall not found in stickynotes

### ISSUE THREAD

**Issue by martinc** [GoogleCloudPlatform/ios-docs-samples#9]
Trying to build the stickynotes Swift RPC sample, and I've gotten pretty far, after installing Protobuf and gRPC from trunk (version 3.0.0-beta-3.1)

However now I'm getting "Expected a type" error in the auto-general protobuf code, it looks like GRPProtoCall class is not found. There is also an error about multiple methods named 'start'.

See attached screenshot

![screen shot 2016-07-18 at 2 49 16 pm](https://cloud.githubusercontent.com/assets/49794/16926477/d83c42be-4cf6-11e6-87c0-e83d264bfb8b.png)

**Comment by timburks** [comment]
Hi Martin, there have been some changes to the code generator that broke this. I'll have an update for you on this soon, probably in the next 24 hours.

**Comment by timburks** [comment]
The samples have been updated to download and use a precompiled protoc that matches the Protobuf library, which should fix this.
